### ISSUE TITLE
04. Continuous Integration and Continuous Deployment (CI/CD)

### ISSUE THREAD

**Issue by wangkelu0** [wangkelu0/CI-CD-Training#1]
# **Event-Driven CI/CD with Hooks**

#### Make the most of your CI/CD with event-driven pipelines.

Just like every application, programming language, framework, and system - all pipelines have internal lifecycles. Internal lifecycles have hooks at key life stages, which can be used to extend built-in functionality or to override it. Because we use _Buildkite_ at REA for our pipelines, we have access to Buildkite's lifecycle hooks.

There are three types of Buildkite hooks:

1. Agent hooks that run for every job on any pipeline
2. Repository hooks that exist in your `.buildkite/hooks` directory
3. Plugin hooks that are provided by any plugins defined in your pipeline file

Each type of hook has unique access and priority to Buildkite lifecycle events, and are powerful tools to utilise.

![Factory production line](https://media.giphy.com/media/11LK0CKzYtkaic/giphy.gif)

| Technical Exposure           | Difficulty Meter (max 5) | How Long Before You Should Ask For Help | Maximum Time You Should Spend On This |
|       :---:                  |      :---:       |              :---:              |  :---:  |
| No exposure to this issue    | :space_invader: :space_invader: :space_invader: |  1 Hour :hourglass_flowing_sand: | 1 Day :sunny: |
| Some exposure to this issue  | :space_invader: :space_invader: | 1 Hour :hourglass_flowing_sand:  | 1 Day :sunny: |
| A lot of exposure this issue | :space_invader: :space_invader: | 1 Hour :hourglass_flowing_sand: | 1 Day :sunny: |

## **Reference Materials**

- [Buildkite Agent Hooks](https://buildkite.com/docs/agent/v3/hooks)
- [Buildkite Agent Plugins](https://pages.git.realestate.com.au/cowbell/buildkite-training/08_hooks_plugins/bk-hooks-plugins.pdf)
- [REA Buildkite Plugins Marketplace](https://rea.to/buildkite-plugins)
- [Code example: A Buildkite plugin](https://git.realestate.com.au/dpearce/wave-buildkite-plugin)
- [Code example: A pre-command hook](https://git.realestate.com.au/dpearce/buildkite-training-pipeline/tree/master/.buildkite/hooks)
- [_Using Components with Known Vulnerabilities_ Entry in the OWASP Top Ten Application Security risks](https://www.owasp.org/index.php/Top_10-2017_A9-Using_Components_with_Known_Vulnerabilities)

------------------------------------------------------------------------------------

## **Buddy System**

These activities are meant to be done with a buddy who has experience in these topics.
If you do not have a buddy allocated for this issue, that's fine - don't stress.
Go speak to your people manager, and they will find you a buddy.

------------------------------------------------------------------------------------

## **Requisite knowledge**

- Git
- GitHub
- Docker
- Docker-Compose
- Bash
- Shipper
- Buildkite

------------------------------------------------------------------------------------

## **Intended outcomes**

After completing this Issue, this is what you should know and be comfortable doing.

- Know what Buildkite pre-command hooks are
- Know what Buildkite plugins are
- Know how to find a proper buildkite plugin in REA
- Know about the pros and cons of pre-command hooks vs plugins
- Be comfortable using both pre-command hooks and plugins in your pipeline
- Be comfortable explaining what the pipeline lifecycle in Buildkite is, and how pre-command hooks and plugins utilise this

------------------------------------------------------------------------------------

## **Questions**

Make sure you have the answers to these questions written down before you start the tasks.

- [ ] What is a Buildkite pre-command hook?
- [ ] What is a Buildkite plugin?
- [ ] In what context would you use a Buildkite pre-command hook vs a Buildkite plugin?
- [ ] What is the Buildkite pipeline lifecycle?

------------------------------------------------------------------------------------

## **Tasks**

Work through these tasks with your buddy.

**NOTE:** While REA prefers the use of Plugin Hooks, having an awareness of how to make Repository Hooks is important for 2 reasons.

1. We do not work with perfect systems all the time, and there will be systems still use Repository Hooks. It is important to know how to use them and how they differ to Plugin Hooks.
2. Sometimes, you will come across a use-case to create your own event-driven pipeline, where a plugin does not exist yet. In this case, you will need to know how to make a Repository Hook (for testing proof of concept), and can then convert this into a great Plugin Hook.

- [ ] Create your own Buildkite pre-command hook to display an emoji or gif before each Buildkite step. Where does it display in the Buildkite Pipeline logs? An example can be found [here](https://git.realestate.com.au/dpearce/buildkite-training-pipeline/tree/master/.buildkite)
- [ ] If you have updated your auto scripts to work with Buildkite, make sure your auto scripts still work on your laptop!

**BONUS CHALLENGE!!**
- [ ] See what other steps can use Buildkite plugins.
- [ ] Create your own Buildkite plugin! Examples are [wave-buildkite-plugin](https://git.realestate.com.au/dpearce/wave-buildkite-plugin) and [docker-image-freshness-buildkite-plugin](https://git.realestate.com.au/buildkite-plugin/docker-image-freshness-buildkite-plugin)
